// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $api_scrapbox_slug_ from "./routes/api/scrapbox/[slug].ts";

import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/api/scrapbox/[slug].ts": $api_scrapbox_slug_,
  },
  islands: {},
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
